---
- name: Get hostname
  hosts: all
  gather_facts: yes

  tasks:
  - name: Get hostname using win_shell
    win_shell: hostname
    register: ComputerName

  - name: Store hostname in a variable
    set_fact:
      my_hostname: "{{ ComputerName.stdout }}"

  - name: write host fact gathered in previous job
    debug: 
      var: my_hostname

  - name: capture host fact in a set_stats var
    set_stats:
      data:
        another_stat: "{{ ComputerName.stdout | map(attribute='ansible_facts.my_hostname') | list }}"
      per_host: no
    
  - name: show set_stats value
    debug:
      var: another_stat