---
- name: Get hostname
  hosts: all
  gather_facts: yes

  tasks:
  - name: Get hostname using win_shell
    win_shell: hostname
    register: ComputerName

  - name: Store hostname in a variable
    set_fact:
      my_hostname: "{{ ComputerName.stdout }}"

  - name: write host fact gathered in previous job
    debug: 
      var: my_hostname