---
- name: Get hostname
  hosts: all
  gather_facts: yes

  tasks:
  - name: Get hostname using win_shell
    win_shell: hostname
    register: ComputerName

  - name: Store hostname in a variable
    set_fact:
      my_hostname: "{{ ComputerName.stdout_lines[0] }}"

  - name: store my_hostname as dictionary in set_stats
    set_stats:
      data:
        some_stat:
          host: "{{ inventory_hostname }}"
          my_hostname: "{{ hostvars[inventory_hostname]['my_hostname'] }}"
      per_host: true

#    set_stats:
#      data: 
#        target_hosts: "{{ target_hosts + [ item.public_dns_name ] }}"
#    loop: "{{ ec2_instance_facts_rhel.instances }}"

  - name: write host fact gathered in previous job
    debug: 
      var: my_hostname
